# Generated by Django 3.2 on 2022-11-23 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('address', models.TextField(max_length=300, null=True)),
                ('is_creator', models.BooleanField(default=False)),
                ('is_verification', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/user_pic/%y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Salat_Time_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosque_name', models.CharField(max_length=200)),
                ('mosque_icon', models.ImageField(null=True, upload_to='')),
                ('Fajr', models.TimeField()),
                ('Sunrise', models.TimeField(blank=True, null=True)),
                ('Dhuhr', models.TimeField()),
                ('Asr', models.TimeField()),
                ('Sunset', models.TimeField(blank=True, null=True)),
                ('Maghrib', models.TimeField()),
                ('Isha', models.TimeField()),
                ('Imsak', models.TimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated')),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(limit_choices_to={'is_creator': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Salat_time', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_Time_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('salat_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salat_id', to='Masjid_Api.salat_time_list')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
