# Generated by Django 3.2 on 2022-11-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salat_time_list',
            name='address',
            field=models.BooleanField(blank=True, max_length=250, null=True),
        ),
    ]
