# Generated by Django 4.1.4 on 2022-12-11 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_Salat_Time_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('Fajr', models.TimeField()),
                ('Sunrise', models.TimeField(blank=True, null=True)),
                ('Dhuhr', models.TimeField()),
                ('Asr', models.TimeField()),
                ('Sunset', models.TimeField(blank=True, null=True)),
                ('Maghrib', models.TimeField()),
                ('Isha', models.TimeField()),
                ('Imsak', models.TimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(limit_choices_to={'is_creator': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Salat_time_1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
