# Generated by Django 3.2 on 2022-10-25 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_time_list',
            name='salat_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salat_id', to='Masjid_Api.salat_time_list'),
        ),
        migrations.AlterField(
            model_name='favorite_time_list',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
