# Generated by Django 3.2 on 2022-10-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0002_auto_20221025_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_time_list',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
