# Generated by Django 3.2 on 2022-11-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0002_salat_time_list_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salat_time_list',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
