# Generated by Django 4.1.4 on 2022-12-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0002_update_salat_time_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='time_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
