# Generated by Django 3.2 on 2022-10-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0003_favorite_time_list_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite_time_list',
            old_name='is_favorite',
            new_name='is_default',
        ),
    ]
