# Generated by Django 3.2 on 2022-11-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0004_rename_is_favorite_favorite_time_list_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salat_time_list',
            name='Asr',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='salat_time_list',
            name='Dhuhr',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='salat_time_list',
            name='Fajr',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='salat_time_list',
            name='Imsak',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salat_time_list',
            name='Isha',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='salat_time_list',
            name='Maghrib',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='salat_time_list',
            name='Sunrise',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salat_time_list',
            name='Sunset',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
