# Generated by Django 3.2 on 2022-12-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0004_user_model_onesignal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, null=True, unique=True)),
                ('time_zone', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
