# Generated by Django 4.1.4 on 2022-12-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0004_update_salat_time_list_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='update_salat_time_list',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
