# Generated by Django 3.2 on 2022-11-22 16:17

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0005_auto_20221101_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='salat_time_list',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}),
        ),
    ]
