# Generated by Django 3.2 on 2022-11-22 16:48

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0006_salat_time_list_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salat_time_list',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': (17.031645, 51.106715), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}),
        ),
    ]
