# Generated by Django 3.2 on 2022-11-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0007_alter_salat_time_list_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salat_time_list',
            name='location',
        ),
    ]
