# Generated by Django 3.2 on 2022-11-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid_Api', '0008_remove_salat_time_list_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='salat_time_list',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salat_time_list',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salat_time_list',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
